#!/bin/bash

echo "Detected current desktop environment: $XDG_CURRENT_DESKTOP"

IFS=':' read -r -a desktops <<< "$XDG_CURRENT_DESKTOP"

for desktop in "${desktops[@]}"; do
  preset_dir="$HOME/.config/waybar/presets/$desktop"
  
  [ -d "$preset_dir" ] || continue
  [ -f "$preset_dir/config.jsonc" ] || continue
  [ -f "$preset_dir/style.css" ] || continue

  echo "Launching waybar using preset dir $preset_dir..."
  exec waybar --config "$preset_dir/config.jsonc" --style "$preset_dir/style.css"
done

echo "No matching Waybar preset found."
exit 1