#!/usr/bin/env python

import asyncio
import json
import signal
from collections.abc import Coroutine
from typing import Any, TypeVar, cast

T = TypeVar("T")


class Bail(Exception): ...


SOCKET_HOST = "localhost"
SOCKET_PORT = 55461
KANATA_FILE = "/tmp/sb-kanata"
WAYBAR_SIGNAL = signal.SIGRTMIN + 17


async def _wait(coro: Coroutine[Any, Any, T], event: asyncio.Event):
    done, pending = await asyncio.wait(
        [
            asyncio.Task(coro, name="wait-coro"),
            asyncio.Task(event.wait(), name="wait-event"),
        ],
        return_when=asyncio.FIRST_COMPLETED,
    )

    task = done.pop()

    try:
        for future in pending:
            future.cancel()
            await future
    except asyncio.CancelledError:
        pass

    if task.get_name() == "wait-event":
        raise Bail()

    return cast(T, task.result())


async def handle_connection(reader: asyncio.StreamReader, event: asyncio.Event):
    while not event.is_set():
        try:
            line = await _wait(reader.readline(), event)
        except Bail:
            return
        if not line:
            return

        line = line.decode().strip()
        if '"LayerChange"' in line:
            print(f"Got layer change event: {line}")
            try:
                data = json.loads(line)
                layer = data.get("LayerChange", {}).get("new", "base")

                with open(KANATA_FILE, "w") as f:
                    if layer != "base":
                        f.write(layer)

                print("Sending kill signal to waybar")
                asyncio.create_task(kill_waybar())
            except json.JSONDecodeError as e:
                print(f"Error decoding JSON: {e}")


async def kill_waybar():
    process = await asyncio.create_subprocess_exec(
        "pkill", f"-{WAYBAR_SIGNAL}", "waybar"
    )
    await process.wait()


def _sigint_callback(event: asyncio.Event):
    print("Received CTRL+C")
    asyncio.get_running_loop().call_soon_threadsafe(lambda: event.set())


async def main():
    event = asyncio.Event()
    signal.signal(signal.SIGINT, lambda *_: _sigint_callback(event))  # type: ignore
    while not event.is_set():
        try:
            reader, _ = await asyncio.open_connection(SOCKET_HOST, SOCKET_PORT)
            await handle_connection(reader, event)
        except (ConnectionRefusedError, asyncio.IncompleteReadError):
            print("Connection lost, retrying in 10 seconds...")
            await asyncio.sleep(10)


if __name__ == "__main__":
    asyncio.run(main())
