#!/usr/bin/env sh

output=$1

get_window_count() {
	idfocused="$(niri msg -j workspaces | jq ".[] | select(.is_active == true and .output == \"$output\" ) | .id")"
	num="$(niri msg -j windows | jq "[.[] | select(.workspace_id == $idfocused)] | length")"
	
    if [ "$num" -eq 0 ]; then
        num=""
    fi

    echo "$num" > /tmp/sb-niri-window-count-$output
    pkill -RTMIN+13 waybar
}

get_window_count

niri msg event-stream |\
    while read -r line; do
        case "$line" in
            "Window opened"*|"Window closed"*|"Workspace focused"*)
		get_window_count
                ;;
        esac
    done