#!/usr/bin/env sh

output=$1

get_column_info() {
    idfocused="$(niri msg -j workspaces | jq -r '.[] | select(.is_active == true and .output == "'"$output"'") | .id')"
    
    if [ -z "$idfocused" ]; then
        echo "" > "/tmp/sb-niri-column-count-$output"
        pkill -RTMIN+13 waybar
        return
    fi

    col_info="$(niri msg -j windows | jq -r --argjson wid "$idfocused" '
        map(select(.workspace_id == $wid)) |
        if length == 0 then
            ""
        else
            (map(.layout.pos_in_scrolling_layout[0]) | max) as $max_col |
            (map(select(.is_focused == true))[0]?.layout?.pos_in_scrolling_layout[0]) as $cur_col |
            if $cur_col then
                "\($cur_col)/\($max_col)"
            else
                "\($max_col)"
            end
        end
    ')"

    echo "$col_info" > "/tmp/sb-niri-column-count-$output"
    pkill -RTMIN+13 waybar
}

get_column_info

niri msg event-stream | \
    while read -r line; do
        case "$line" in
            *"Window opened"*|*"Window closed"*|*"Workspace focused"*|*"focus"*|*"layouts"*)
                get_column_info
                ;;
        esac
    done
