#!/usr/bin/env bash

TMPFILE="/tmp/sb-spotify"
[ -f "$TMPFILE" ] && rm -f "$TMPFILE"

playerctl --player=spotify metadata --format '{{status}}|{{artist}} - {{title}}' --follow |
  stdbuf -oL awk -F'|' '{ print ($1 == "Playing") ? $2 : ""; fflush() }' |
  while IFS= read -r line; do
    cutline=$(. $HOME/.config/waybar/modules/strcut 40 "$line")
    escaped=$(echo "$cutline" | sed 's/&/\&amp;/g' | sed 's/</\&lt;/g' | sed 's/>/\&gt;/g')
    echo "$escaped" > "$TMPFILE"
    pkill -RTMIN+18 waybar
  done